# Generated by Django 3.0.7 on 2020-06-15 14:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('notes', models.CharField(blank=True, max_length=2048, null=True)),
                ('contact', models.CharField(max_length=2048)),
                ('email', models.CharField(max_length=2048, validators=[django.core.validators.EmailValidator])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FinancialActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('notes', models.CharField(blank=True, max_length=2048, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=2048, null=True)),
                ('invoice_date', models.DateTimeField(blank=True, max_length=2048, null=True)),
                ('incoming', models.IntegerField(default=0)),
                ('charge', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('notes', models.CharField(blank=True, max_length=2048, null=True)),
                ('name', models.CharField(max_length=2048)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plan.Customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('notes', models.CharField(blank=True, max_length=2048, null=True)),
                ('desc', models.CharField(blank=True, max_length=2048, null=True)),
                ('days', models.IntegerField()),
                ('type', models.CharField(choices=[('new', 'new'), ('open', 'open'), ('closed', 'closed')], max_length=2048)),
                ('status', models.CharField(choices=[('web', 'web'), ('mobile', 'mobile')], max_length=2048)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SaleActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('notes', models.CharField(blank=True, max_length=2048, null=True)),
                ('desc', models.CharField(max_length=2048)),
                ('days', models.IntegerField()),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('web', 'web'), ('mobile', 'mobile')], max_length=2048)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('notes', models.CharField(blank=True, max_length=2048, null=True)),
                ('desc', models.CharField(max_length=2048)),
                ('financial_activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='plan.FinancialActivity')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BillingActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('notes', models.CharField(blank=True, max_length=2048, null=True)),
                ('desc', models.CharField(max_length=2048)),
                ('days', models.IntegerField(blank=True, null=True)),
                ('financial_activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='plan.FinancialActivity')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
