# Generated by Django 3.0.7 on 2020-06-18 09:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200618_0915'),
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('notes', models.CharField(blank=True, max_length=2048, null=True)),
                ('desc', models.CharField(max_length=2048)),
                ('days', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('notes', models.CharField(blank=True, max_length=2048, null=True)),
                ('contact', models.CharField(max_length=2048)),
                ('email', models.EmailField(max_length=2048)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FinancialActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('notes', models.CharField(blank=True, max_length=2048, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=2048, null=True)),
                ('invoice_date', models.DateTimeField(blank=True, max_length=2048, null=True)),
                ('incoming', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('charge', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(0)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('notes', models.CharField(blank=True, max_length=2048, null=True)),
                ('name', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('new', 'new'), ('open', 'open'), ('closed', 'closed')], max_length=2048)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plan.Customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('notes', models.CharField(blank=True, max_length=2048, null=True)),
                ('desc', models.CharField(max_length=2048)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SaleActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('notes', models.CharField(blank=True, max_length=2048, null=True)),
                ('desc', models.CharField(max_length=2048)),
                ('days', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('new', 'new'), ('open', 'open'), ('closed', 'closed')], max_length=2048)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('notes', models.CharField(blank=True, max_length=2048, null=True)),
                ('desc', models.CharField(blank=True, max_length=2048, null=True)),
                ('days', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('type', models.CharField(choices=[('web', 'web'), ('mobile', 'mobile')], max_length=2048)),
                ('status', models.CharField(choices=[('new', 'new'), ('open', 'open'), ('closed', 'closed')], max_length=2048)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Project')),
                ('users', models.ManyToManyField(to='users.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkLogActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('notes', models.CharField(blank=True, max_length=2048, null=True)),
                ('desc', models.CharField(max_length=128)),
                ('day', models.DateField(default=django.utils.timezone.now)),
                ('hours', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('work_activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plan.WorkActivity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='billingactivity',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Project'),
        ),
    ]
