# Generated by Django 3.0.7 on 2020-06-15 15:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingactivity',
            name='days',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='financialactivity',
            name='charge',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='financialactivity',
            name='incoming',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='saleactivity',
            name='days',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='saleactivity',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='workactivity',
            name='days',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='WorkLogActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('notes', models.CharField(blank=True, max_length=2048, null=True)),
                ('desc', models.CharField(max_length=2048)),
                ('day', models.DateField(default=django.utils.timezone.now)),
                ('hours', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('work_activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plan.WorkActivity')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
