# Generated by Django 3.0.7 on 2020-06-19 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_auto_20200618_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingactivity',
            name='financial_activity',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='plan.FinancialActivity'),
            preserve_default=False,
        ),
    ]
