# Generated by Django 3.0.7 on 2020-06-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_auto_20200616_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('open', 'open'), ('closed', 'closed')], max_length=2048),
        ),
        migrations.AlterField(
            model_name='saleactivity',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('open', 'open'), ('closed', 'closed')], max_length=2048),
        ),
        migrations.AlterField(
            model_name='workactivity',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('open', 'open'), ('closed', 'closed')], max_length=2048),
        ),
        migrations.AlterField(
            model_name='workactivity',
            name='type',
            field=models.CharField(choices=[('web', 'web'), ('mobile', 'mobile')], max_length=2048),
        ),
    ]
