# Generated by Django 3.0.7 on 2020-06-17 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_auto_20200616_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingactivity',
            name='financial_activity',
        ),
        migrations.RemoveField(
            model_name='purchaseactivity',
            name='financial_activity',
        ),
    ]
